version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cssnano
    versions:
    - 4.1.11
    - 5.0.1
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
    - 10.2.5
  - dependency-name: gulp-postcss
    versions:
    - 9.0.0
