name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'dependencies'
      - 'security'
exclude-labels:
  - 'invalid'
  - 'Stale PR'
  - 'duplicate'
  - 'wontfix'
  - 'github-action'
change-template: '- #$NUMBER $TITLE (@$AUTHOR)'
version-resolver:
  major:
    labels:
      - 'feature'
      - 'enhancement'
      - 'major'
  minor:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'minor'
  patch:
    labels:
      - 'dependencies'
      - 'security'
      - 'patch'
  default: minor
template: |
  ## Changes in this release

  $CHANGES

  ## Contributors to this release

  $CONTRIBUTORS

  ## Previous tag

  $PREVIOUS_TAG
no-changes-template: |
  Confusingly, there were no changes in this release
