categories:
  - title: 'Features/Enhancements'
    collapse-after: 5
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Fixes'
    collapse-after: 3
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    collapse-after: 2
    labels:
      - 'dependencies'
      - 'security'
      - 'github-action'
exclude-labels:
  - 'invalid'
  - 'Stale PR'
  - 'duplicate'
  - 'wontfix'
version-resolver:
  major:
    labels:
      - 'feature'
      - 'enhancement'
      - 'major'
  minor:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'minor'
  patch:
    labels:
      - 'dependencies'
      - 'security'
      - 'patch'
      - 'github-action'
  default: patch
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH$PRERELEASE'
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
template: |
  ## Changes
  $CHANGES

  **Contributors**
  $CONTRIBUTORS

  **Previously:** [$PREVIOUS_TAG](https://github.com/AdamJ/AdamJ.github.io/releases/tag/$PREVIOUS_TAG)

  [All Tags](https://github.com/AdamJ/AdamJ.github.io/tags)
  [All Releases](https://github.com/AdamJ/AdamJ.github.io/releases)
no-changes-template: |
  Nothing to see here...
