packages:
  - "src/**"

allowBuilds:
  '@parcel/watcher': true
  canvas: true
  highlight.js: true
  sharp: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "canvas"
  - "highlight.js"
  - "sharp"
  - "turndown"
