module.exports = {
  env: process.env.ELEVENTY_ENV,
  url: process.env.URL || "http://localhost:8080",
  siteName: "Adam Jolicoeur",
  siteDescription: "Product Designer who ships code—and understands the business side.",
  siteURL: "https://www.adamjolicoeur.com",
  authorName: "Adam J. Jolicoeur",
  siteMeta:"Adam, Adam Jolicoeur, Adam J. Jolicoeur, AdamJ, Jolicoeur, adamjolicoeur.com, www.adamjolicoeur.com, mindreeper2420, Portfolio, Design, Product Designer, UXD, UX Designer, UX Developer, UX Engineer, Design Technologist, Product Mangement, CSS",
  packageVersion: "packageVersion",
  blueskyUsername: "adamjol.bsky.social",
  blueskyTitle: "Adam Jolicoeur - Product Designer Who Ships Code",
  blueskyDescription: "Product Designer who ships code—and understands the business side.",
  githubURL: "https://github.com/AdamJ",
  githubUsername: "AdamJ",
  githubDescription: "Follow my work in the open source community.",
  linkedinURL: "https://www.linkedin.com/in/ajjolicoeur/",
  linkedinDescription: "Product Designer | Design Systems Expert | AWS & Red Hat Alum | I design enterprise apps and code prototypes (HTML/CSS/React)",
  devtoURL: "https://dev.to/adamj",
  mastodonUsername: "@adamjol@mastodon.world",
  codepenURL: "https://codepen.io/AdamJolicoeur",
  figmaURL: "https://figma.com/@AdamJ",
  blogURL: "https://blog.adamjolicoeur.com"
};
