module.exports = {
  url: process.env.URL || "http://localhost:8080",
  siteName: "Adam Jolicoeur",
  siteDescription: "The portfolio site for Adam Jolicoeur.",
  authorName: "Adam J. Jolicoeur",
  siteMeta:"Adam, Adam Jolicoeur, Adam J. Jolicoeur, AdamJ, Jolicoeur, adamjolicoeur.com, www.adamjolicoeur.com, mindreeper2420, Portfolio, Design, UXD, UX Designer, UX Developer, UX Engineer, Design Technologist, CSS",
  packageVersion: "packageVersion",
  blueskyUsername: "adamjol.bsky.social",
  blueskyTitle: "Adam Jolicoeur - User Experience Designer and Developer",
  blueskyDescription: "Driven and passionate user experience designer with a background in software development. Looking for a role where I can continue to utilize my UX/UI skills and create interfaces that will allows users to perform their work seamlessly.",
  githubURL: "https://github.com/AdamJ",
  githubUsername: "AdamJ",
  githubDescription: "Follow my work in the open source community.",
  linkedinURL: "https://www.linkedin.com/in/ajjolicoeur/",
  linkedinDescription: "Lead Program Manager and UX Designer",
  devtoURL: "https://dev.to/adamj",
  mastodonUsername: "@adamjol@mastodon.world",
  codepenURL: "https://codepen.io/AdamJolicoeur",
  figmaURL: "https://figma.com/@AdamJ"
};
