module.exports = {
  env: process.env.ELEVENTY_ENV,
  url: process.env.URL || "http://localhost:8080",
  siteName: "Adam Jolicoeur",
  siteDescription: "Product designer building AI-native products, from interaction patterns to the systems that govern them.",
  siteURL: "https://www.adamjolicoeur.com",
  authorName: "Adam J. Jolicoeur",
  siteMeta:"Adam, Adam Jolicoeur, Adam J. Jolicoeur, AdamJ, Jolicoeur, adamjolicoeur.com, www.adamjolicoeur.com, mindreeper2420, Portfolio, Design, Product Designer, UXD, UX Designer, UX Developer, UX Engineer, Design Technologist, Product Mangement, CSS",
  packageVersion: "packageVersion",
  blueskyUsername: "adamjol.bsky.social",
  blueskyTitle: "Adam Jolicoeur: Product Designer for Enterprise Systems and AI",
  blueskyDescription: "Product designer building AI-native products, from interaction patterns to the systems that govern them.",
  githubURL: "https://github.com/AdamJ",
  githubUsername: "AdamJ",
  githubDescription: "Follow my work in the open source community.",
  linkedinURL: "https://www.linkedin.com/in/ajjolicoeur/",
  linkedinDescription: "Product Designer | Design Systems | AI-Native Products | AWS & Red Hat Alum | 15+ years designing complex enterprise software",
  devtoURL: "https://dev.to/adamj",
  mastodonUsername: "@adamjol@mastodon.world",
  codepenURL: "https://codepen.io/AdamJolicoeur",
  figmaURL: "https://figma.com/@AdamJ",
  blogURL: "https://blog.adamjolicoeur.com"
};
