name: Eleventy Build

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3.6.0
        - name: Setup Node
          uses: actions/setup-node@v3.8.1
          with:
            node-version: '18.x'
        - run: npm ci
        - run: npm run build
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3.9.3
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_dir: ./docs
            publish_branch: gh-pages
