name: Eleventy Build

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v6

        - name: Setup Node
          uses: actions/setup-node@v6
          with:
            node-version: '25.9.0'

        - name: Install pnpm
          run: |
            npm install -g pnpm
            npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONT_AWESOME_TOKEN }}"
            pnpm install --ignore-scripts

        - name: Run Build
          run: pnpm build

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3.9.3
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_dir: ./docs
            publish_branch: gh-pages
            commit_message: ${{ github.event.head_commit.message }}
