name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale. Please update or close.'
        stale-pr-message: 'This pull request is stale. Either update or close.'
        stale-issue-label: 'Stale issue'
        stale-pr-label: 'Stale PR'
